print ('Exemplo de coleta de dados')
nome= input('Qual é o seu nome?')
idade= input('Qual é a sua idade?')
peso= input('Qual é o seu peso?')
altura= input('Qual é a sua altura?')
print('os dados coletados foram', 'nome:',nome,'idade',idade,'peso',peso,'altura',altura)
